#ifndef PRAGMA_CRC_LIB_H
#define PRAGMA_CRC_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_CRC_PROTOS_H
#include <clib/crc_protos.h>
#endif /* CLIB_CRC_PROTOS_H */

/*"crc.library" */
#pragma amicall(CRCBase, 0x1E, DoCRC32_1(a0,d0))
#pragma amicall(CRCBase, 0x24, DoCRC32_2(a0,d0))
#pragma amicall(CRCBase, 0x2A, DoCRC32_3(a0,d0))
#pragma amicall(CRCBase, 0x30, DoCRC32_4(a0,d0))
#pragma amicall(CRCBase, 0x36, DoCRC32_5(a0,d0))
#pragma amicall(CRCBase, 0x3C, DoCRC32_6(a0,d0))
#pragma amicall(CRCBase, 0x42, DoCRC16_1(a0,d0))
#pragma amicall(CRCBase, 0x48, DoCRC16_2(a0,d0))
#pragma amicall(CRCBase, 0x4E, DoCRC16_3(a0,d0))
#pragma amicall(CRCBase, 0x54, DoCRC16_4(a0,d0))
#pragma amicall(CRCBase, 0x5A, DoCHS32_1M(a0,d0))
#pragma amicall(CRCBase, 0x60, DoCHS32_1I(a0,d0))
#pragma amicall(CRCBase, 0x66, DoCHS32_2(a0,d0))
#pragma amicall(CRCBase, 0x6C, DoCHS16_1(a0,d0))
#pragma amicall(CRCBase, 0x72, DoEORB(a0,d0))
#pragma amicall(CRCBase, 0x78, DoEORWM(a0,d0))
#pragma amicall(CRCBase, 0x7E, DoEORWI(a0,d0))
#pragma amicall(CRCBase, 0x84, DoEORLM(a0,d0))
#pragma amicall(CRCBase, 0x8A, DoEORLI(a0,d0))
#pragma amicall(CRCBase, 0x90, DoSumSB(a0,d0))
#pragma amicall(CRCBase, 0x96, DoSumSWM(a0,d0))
#pragma amicall(CRCBase, 0x9C, DoSumSWI(a0,d0))
#pragma amicall(CRCBase, 0xA2, DoSumUB(a0,d0))
#pragma amicall(CRCBase, 0xA8, DoSumUWM(a0,d0))
#pragma amicall(CRCBase, 0xAE, DoSumUWI(a0,d0))
#pragma amicall(CRCBase, 0xB4, DoSumLM(a0,d0))
#pragma amicall(CRCBase, 0xBA, DoSumLI(a0,d0))
#pragma amicall(CRCBase, 0xC0, md5sum(a0,d0,a1))

#endif /* PRAGMA_CRC_LIB_H */
