#ifndef PRAGMAS_CRC_PRAGMAS_H
#define PRAGMAS_CRC_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_CRC_PROTOS_H
#include <clib/crc_protos.h>
#endif /* CLIB_CRC_PROTOS_H */

/*"crc.library" */
#pragma libcall CRCBase DoCRC32_1 1E 0802
#pragma libcall CRCBase DoCRC32_2 24 0802
#pragma libcall CRCBase DoCRC32_3 2A 0802
#pragma libcall CRCBase DoCRC32_4 30 0802
#pragma libcall CRCBase DoCRC32_5 36 0802
#pragma libcall CRCBase DoCRC32_6 3C 0802
#pragma libcall CRCBase DoCRC16_1 42 0802
#pragma libcall CRCBase DoCRC16_2 48 0802
#pragma libcall CRCBase DoCRC16_3 4E 0802
#pragma libcall CRCBase DoCRC16_4 54 0802
#pragma libcall CRCBase DoCHS32_1M 5A 0802
#pragma libcall CRCBase DoCHS32_1I 60 0802
#pragma libcall CRCBase DoCHS32_2 66 0802
#pragma libcall CRCBase DoCHS16_1 6C 0802
#pragma libcall CRCBase DoEORB 72 0802
#pragma libcall CRCBase DoEORWM 78 0802
#pragma libcall CRCBase DoEORWI 7E 0802
#pragma libcall CRCBase DoEORLM 84 0802
#pragma libcall CRCBase DoEORLI 8A 0802
#pragma libcall CRCBase DoSumSB 90 0802
#pragma libcall CRCBase DoSumSWM 96 0802
#pragma libcall CRCBase DoSumSWI 9C 0802
#pragma libcall CRCBase DoSumUB A2 0802
#pragma libcall CRCBase DoSumUWM A8 0802
#pragma libcall CRCBase DoSumUWI AE 0802
#pragma libcall CRCBase DoSumLM B4 0802
#pragma libcall CRCBase DoSumLI BA 0802
#pragma libcall CRCBase DoMD5Sum C0 90803
/*--- functions in V2 or higher --- */
#pragma libcall CRCBase DoSHA1 C6 90803
#pragma libcall CRCBase DoSHA256 CC 90803
#pragma libcall CRCBase DoCHS16_2 D2 0802
#pragma libcall CRCBase DoCHS16_3 D8 0802
#pragma libcall CRCBase DoCRC32_7 DE 0802
#pragma libcall CRCBase CRCReserved1 E4 0802
#pragma libcall CRCBase CRCReserved2 EA 0802
#pragma libcall CRCBase CRCReserved3 F0 0802
#pragma libcall CRCBase CRCReserved4 F6 0802
#pragma libcall CRCBase CRCNew FC 001
#pragma libcall CRCBase CRCReset 102 801
#pragma libcall CRCBase CRCUpdate 108 09803
#pragma libcall CRCBase CRCFinal 10E 9802
#pragma libcall CRCBase CRCDispose 114 801
#pragma libcall CRCBase CRCDigestLength 11A 001

#endif /* PRAGMAS_CRC_PRAGMAS_H */
