#ifndef INLINE_CRC_H
#define INLINE_CRC_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"crc.library" */
#define DoCRC32_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_3(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_4(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_5(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_6(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_3(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_4(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_1M(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_1I(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS16_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORLM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORLI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register BYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-168:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-174:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumLM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-180:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumLI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-186:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define md5sum(Mem, Size, md5sum)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register UBYTE *p2 __asm("a1") = (md5sum);   \
	__asm volatile ("jsr a6@(-192:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})


#endif /* INLINE_CRC_H */
