#ifndef PROTO_CRC_H
#define PROTO_CRC_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/crc_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * CRCBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_CRC_PRAGMAS_H
#include <pragmas/crc_pragmas.h>
#endif /* PRAGMAS_CRC_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_CRC_LIB_H
#include <pragma/crc_lib.h>
#endif /* PRAGMA_CRC_LIB_H */

#elif defined(__VBCC__)

#include <clib/crc_protos.h>

#ifndef INLINE_CRC_PROTOS_H
#include <inline/crc_protos.h>
#endif /* INLINE_CRC_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_CRC_H
#include <inline/crc.h>
#endif /* INLINE_CRC_H */
#else
#include <clib/crc_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/crc_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_CRC_H */
