#ifndef INLINE_CRC_H
#define INLINE_CRC_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"crc.library" */
#define DoCRC32_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_3(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_4(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_5(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_6(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_3(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC16_4(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_1M(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_1I(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS32_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS16_1(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORLM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoEORLI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register BYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumSWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUB(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUWM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-168:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumUWI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-174:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumLM(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-180:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoSumLI(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-186:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoMD5Sum(Mem, Size, Digest)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register UBYTE *p2 __asm("a1") = (Digest);   \
	__asm volatile ("jsr a6@(-192:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

/*--- functions in V2 or higher --- */
#define DoSHA1(Mem, Size, Digest)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register UBYTE *p2 __asm("a1") = (Digest);   \
	__asm volatile ("jsr a6@(-198:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define DoSHA256(Mem, Size, Digest)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register UBYTE *p2 __asm("a1") = (Digest);   \
	__asm volatile ("jsr a6@(-204:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define DoCHS16_2(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-210:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCHS16_3(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-216:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DoCRC32_7(Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register UBYTE *p0 __asm("a0") = (Mem);   \
	register LONG p1 __asm("d0") = (Size);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-222:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define CRCNew(type)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register ULONG p0 __asm("d0") = (type);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-252:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define CRCReset(handle)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register APTR p0 __asm("a0") = (handle);   \
	__asm volatile ("jsr a6@(-258:W);" : "+r"(b) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define CRCUpdate(handle, Mem, Size)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register APTR p0 __asm("a0") = (handle);   \
	register UBYTE *p1 __asm("a1") = (Mem);   \
	register LONG p2 __asm("d0") = (Size);   \
	__asm volatile ("jsr a6@(-264:W);" : "+r"(b) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define CRCFinal(handle, Digest)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register APTR p0 __asm("a0") = (handle);   \
	register UBYTE *p1 __asm("a1") = (Digest);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-270:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define CRCDispose(handle)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register APTR p0 __asm("a0") = (handle);   \
	__asm volatile ("jsr a6@(-276:W);" : "+r"(b) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define CRCDigestLength(type)    \
({  \
	register void *b __asm("a6") = CRCBase;  \
	register ULONG p0 __asm("d0") = (type);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-282:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


#endif /* INLINE_CRC_H */
