#ifndef INLINE_CRC_PROTOS_H
#define INLINE_CRC_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"crc.library" */
ULONG __DoCRC32_1(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-30(a6)";
#define DoCRC32_1(Mem, Size) __DoCRC32_1(CRCBase, (Mem), (Size))

ULONG __DoCRC32_2(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-36(a6)";
#define DoCRC32_2(Mem, Size) __DoCRC32_2(CRCBase, (Mem), (Size))

ULONG __DoCRC32_3(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-42(a6)";
#define DoCRC32_3(Mem, Size) __DoCRC32_3(CRCBase, (Mem), (Size))

ULONG __DoCRC32_4(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-48(a6)";
#define DoCRC32_4(Mem, Size) __DoCRC32_4(CRCBase, (Mem), (Size))

ULONG __DoCRC32_5(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-54(a6)";
#define DoCRC32_5(Mem, Size) __DoCRC32_5(CRCBase, (Mem), (Size))

ULONG __DoCRC32_6(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-60(a6)";
#define DoCRC32_6(Mem, Size) __DoCRC32_6(CRCBase, (Mem), (Size))

UWORD __DoCRC16_1(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-66(a6)";
#define DoCRC16_1(Mem, Size) __DoCRC16_1(CRCBase, (Mem), (Size))

UWORD __DoCRC16_2(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-72(a6)";
#define DoCRC16_2(Mem, Size) __DoCRC16_2(CRCBase, (Mem), (Size))

UWORD __DoCRC16_3(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-78(a6)";
#define DoCRC16_3(Mem, Size) __DoCRC16_3(CRCBase, (Mem), (Size))

UWORD __DoCRC16_4(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-84(a6)";
#define DoCRC16_4(Mem, Size) __DoCRC16_4(CRCBase, (Mem), (Size))

ULONG __DoCHS32_1M(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-90(a6)";
#define DoCHS32_1M(Mem, Size) __DoCHS32_1M(CRCBase, (Mem), (Size))

ULONG __DoCHS32_1I(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-96(a6)";
#define DoCHS32_1I(Mem, Size) __DoCHS32_1I(CRCBase, (Mem), (Size))

ULONG __DoCHS32_2(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-102(a6)";
#define DoCHS32_2(Mem, Size) __DoCHS32_2(CRCBase, (Mem), (Size))

UWORD __DoCHS16_1(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-108(a6)";
#define DoCHS16_1(Mem, Size) __DoCHS16_1(CRCBase, (Mem), (Size))

UBYTE __DoEORB(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-114(a6)";
#define DoEORB(Mem, Size) __DoEORB(CRCBase, (Mem), (Size))

UWORD __DoEORWM(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-120(a6)";
#define DoEORWM(Mem, Size) __DoEORWM(CRCBase, (Mem), (Size))

UWORD __DoEORWI(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-126(a6)";
#define DoEORWI(Mem, Size) __DoEORWI(CRCBase, (Mem), (Size))

ULONG __DoEORLM(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-132(a6)";
#define DoEORLM(Mem, Size) __DoEORLM(CRCBase, (Mem), (Size))

ULONG __DoEORLI(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-138(a6)";
#define DoEORLI(Mem, Size) __DoEORLI(CRCBase, (Mem), (Size))

ULONG __DoSumSB(__reg("a6") void *, __reg("a0") BYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-144(a6)";
#define DoSumSB(Mem, Size) __DoSumSB(CRCBase, (Mem), (Size))

ULONG __DoSumSWM(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-150(a6)";
#define DoSumSWM(Mem, Size) __DoSumSWM(CRCBase, (Mem), (Size))

ULONG __DoSumSWI(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-156(a6)";
#define DoSumSWI(Mem, Size) __DoSumSWI(CRCBase, (Mem), (Size))

ULONG __DoSumUB(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-162(a6)";
#define DoSumUB(Mem, Size) __DoSumUB(CRCBase, (Mem), (Size))

ULONG __DoSumUWM(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-168(a6)";
#define DoSumUWM(Mem, Size) __DoSumUWM(CRCBase, (Mem), (Size))

ULONG __DoSumUWI(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-174(a6)";
#define DoSumUWI(Mem, Size) __DoSumUWI(CRCBase, (Mem), (Size))

ULONG __DoSumLM(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-180(a6)";
#define DoSumLM(Mem, Size) __DoSumLM(CRCBase, (Mem), (Size))

ULONG __DoSumLI(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size)="\tjsr\t-186(a6)";
#define DoSumLI(Mem, Size) __DoSumLI(CRCBase, (Mem), (Size))

void __md5sum(__reg("a6") void *, __reg("a0") UBYTE *Mem, __reg("d0") LONG Size, __reg("a1") UBYTE *md5sum)="\tjsr\t-192(a6)";
#define md5sum(Mem, Size, md5sum) __md5sum(CRCBase, (Mem), (Size), (md5sum))


#endif /* INLINE_CRC_PROTOS_H */
