#ifndef CLIB_CRC_PROTOS_H
#define CLIB_CRC_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef LIBRARIES_CRC_H
#include <libraries/crc.h>
#endif

/*"crc.library"*/
ULONG DoCRC32_1(UBYTE *Mem, LONG Size);
ULONG DoCRC32_2(UBYTE *Mem, LONG Size);
ULONG DoCRC32_3(UBYTE *Mem, LONG Size);
ULONG DoCRC32_4(UBYTE *Mem, LONG Size);
ULONG DoCRC32_5(UBYTE *Mem, LONG Size);
ULONG DoCRC32_6(UBYTE *Mem, LONG Size);
UWORD DoCRC16_1(UBYTE *Mem, LONG Size);
UWORD DoCRC16_2(UBYTE *Mem, LONG Size);
UWORD DoCRC16_3(UBYTE *Mem, LONG Size);
UWORD DoCRC16_4(UBYTE *Mem, LONG Size);
ULONG DoCHS32_1M(UBYTE *Mem, LONG Size);
ULONG DoCHS32_1I(UBYTE *Mem, LONG Size);
ULONG DoCHS32_2(UBYTE *Mem, LONG Size);
UWORD DoCHS16_1(UBYTE *Mem, LONG Size);
UBYTE DoEORB(UBYTE *Mem, LONG Size);
UWORD DoEORWM(UBYTE *Mem, LONG Size);
UWORD DoEORWI(UBYTE *Mem, LONG Size);
ULONG DoEORLM(UBYTE *Mem, LONG Size);
ULONG DoEORLI(UBYTE *Mem, LONG Size);
ULONG DoSumSB(BYTE *Mem, LONG Size);
ULONG DoSumSWM(UBYTE *Mem, LONG Size);
ULONG DoSumSWI(UBYTE *Mem, LONG Size);
ULONG DoSumUB(UBYTE *Mem, LONG Size);
ULONG DoSumUWM(UBYTE *Mem, LONG Size);
ULONG DoSumUWI(UBYTE *Mem, LONG Size);
ULONG DoSumLM(UBYTE *Mem, LONG Size);
ULONG DoSumLI(UBYTE *Mem, LONG Size);
void md5sum(UBYTE *Mem, LONG Size, UBYTE *md5sum);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_CRC_PROTOS_H */
